
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author david
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_agact = new javax.swing.JDialog();
        cb_actividades = new javax.swing.JComboBox<>();
        tf_nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        sp_duracion = new javax.swing.JSpinner();
        sp_posibilidades = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        cb_proyectos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_proyecto = new javax.swing.JTree();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        cb_actividades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none" }));

        jLabel2.setText("nombre");

        jLabel3.setText("duracion");

        jLabel4.setText("posibilidades de retrazo");

        jButton3.setText("guardar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_agactLayout = new javax.swing.GroupLayout(jd_agact.getContentPane());
        jd_agact.getContentPane().setLayout(jd_agactLayout);
        jd_agactLayout.setHorizontalGroup(
            jd_agactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agactLayout.createSequentialGroup()
                .addGroup(jd_agactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_agactLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jd_agactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(48, 48, 48)
                        .addGroup(jd_agactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nombre)
                            .addComponent(cb_actividades, 0, 131, Short.MAX_VALUE)
                            .addComponent(sp_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sp_posibilidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_agactLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jButton3)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jd_agactLayout.setVerticalGroup(
            jd_agactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agactLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(cb_actividades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(jd_agactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_agactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(sp_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_agactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(sp_posibilidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(31, 31, 31))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Proyectos");

        cb_proyectos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none" }));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("proyectos");
        jt_proyecto.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jt_proyecto);

        jButton1.setText("agregar proyecto");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("agregar actividad");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_proyectos, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(249, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cb_proyectos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String n = JOptionPane.showInputDialog("nombre del proyecto");
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_proyectos.getModel();
        modelo.addElement(new proyectos(n));
        cb_proyectos.setModel(modelo);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        try {
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_proyectos.getModel();
            if (((proyectos) modelo.getElementAt(cb_proyectos.getSelectedIndex())).getActi().isEmpty()) {

            } else {
                DefaultComboBoxModel m = (DefaultComboBoxModel) cb_actividades.getModel();
                m.removeAllElements();
                for (int i = 0; i < ((proyectos) modelo.getElementAt(cb_proyectos.getSelectedIndex())).getActi().size(); i++) {
                    m.addElement((actividades) ((proyectos) modelo.getElementAt(cb_proyectos.getSelectedIndex())).getActi().get(i));
                }
                m.addElement("none");
                cb_actividades.setModel(m);
            }
            jd_agact.setModal(true);
            jd_agact.pack();
            jd_agact.setLocationRelativeTo(this);
            jd_agact.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        try {
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_proyectos.getModel();
            if (cb_actividades.getSelectedItem().toString().equals("ninguna")) {
                ((proyectos) modelo.getElementAt(cb_proyectos.getSelectedIndex())).getActi().add(new actividades(tf_nombre.getText(), (Integer) sp_duracion.getValue(), (Integer) sp_posibilidades.getValue()));
                ((proyectos) modelo.getElementAt(cb_proyectos.getSelectedIndex())).getActi().get(((proyectos) modelo.getElementAt(cb_proyectos.getSelectedIndex())).getActi().size() - 1).setIniciotemp(1);
                cb_proyectos.setModel(modelo);
                JOptionPane.showMessageDialog(jd_agact, "actividad creada");
                jd_agact.setVisible(false);
                actualizar();
            } else {
                DefaultComboBoxModel m = (DefaultComboBoxModel) cb_actividades.getModel();
                ((proyectos) modelo.getElementAt(cb_proyectos.getSelectedIndex())).getActi().add(new actividades(tf_nombre.getText(), (Integer) sp_duracion.getValue(), (Integer) sp_posibilidades.getValue()));
                ((actividades) m.getElementAt(cb_actividades.getSelectedIndex())).getPredecesoras().add((actividades) ((proyectos) modelo.getElementAt(cb_proyectos.getSelectedIndex())).getActi().get(((proyectos) modelo.getElementAt(cb_proyectos.getSelectedIndex())).getActi().size() - 1));
                ((proyectos)modelo.getElementAt(cb_proyectos.getSelectedIndex())).getActi().get(((proyectos)modelo.getElementAt(cb_proyectos.getSelectedIndex())).getActi().size()-1).getSucesoras().add((actividades)m.getElementAt(cb_actividades.getSelectedIndex()));
                cb_proyectos.setModel(modelo);
                cb_actividades.setModel(m);
                JOptionPane.showMessageDialog(jd_agact, "actividad creada");
                jd_agact.setVisible(false);
                actualizar();
            }
            tf_nombre.setText("");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_actividades;
    private javax.swing.JComboBox<String> cb_proyectos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JDialog jd_agact;
    private javax.swing.JTree jt_proyecto;
    private javax.swing.JSpinner sp_duracion;
    private javax.swing.JSpinner sp_posibilidades;
    private javax.swing.JTextField tf_nombre;
    // End of variables declaration//GEN-END:variables

    public void actualizar() {
        try {
            proyectos p = (proyectos) cb_proyectos.getSelectedItem();
            DefaultTreeModel m = (DefaultTreeModel) jt_proyecto.getModel();
            DefaultMutableTreeNode r = new DefaultMutableTreeNode(p);
            m.setRoot(r);
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
            raiz.removeAllChildren();
            DefaultMutableTreeNode n1 = null;
            DefaultMutableTreeNode n2 = null;
            DefaultMutableTreeNode n3 = null;
            for (actividades t : p.getActi()) {
                if (t.getPredecesoras().isEmpty() && t.getSucesoras().isEmpty()) {
                    n1 = new DefaultMutableTreeNode(t);
                    raiz.add(n1);
                } else {
                    for (actividades s : t.getPredecesoras()) {
                        n2 = new DefaultMutableTreeNode(s);
                        for (actividades c : s.getSucesoras()) {
                            n3 = new DefaultMutableTreeNode(c);
                            n3.add(n2);
                        }
                        raiz.add(n3);
                    }

                }
            }
            m.reload();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
